server:
  port: 33331
dubbo:
  application:
    name: base-api
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20800

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yhjaicly
  redis:
    host: localhost
    port: 6379

    # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置中心
nacos:
  config:
    server-addr: 127.0.0.1:8848
    data-id: hai
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
    auto-refresh: true