server:
  port: 8889

netty:
  address: 127.0.0.1
  port: 5679
  path: /chat

spring:
  application:
    name: netty-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #注册服务到nacos
  redis:
    host: 127.0.0.1
    port: 6379